import { HabitIcon } from 'Components/Icon/Icon.types';
import { Colour } from 'Types/Colour.types';
import { EVERYDAY_SCHEDULE } from 'Types/Habit.constants';
import { HabitObject } from 'Types/Habit.types';

export interface CategoryObject {
    id: CategoryType;
    name: string;
    icon: HabitIcon;
    colour: Colour;
    habits: HabitObject[];
}

export type CategoryType =
    | 'health'
    | 'wellbeing'
    | 'intellect'
    | 'organisation'
    | 'social'
    | 'diet'
    | 'art'
    | 'finance'
    | 'thoughful'
    | 'thankful';

export type AllCategories = {
    [category in CategoryType]: CategoryObject;
};

export const Categories: AllCategories = {
    health: {
        id: 'health',
        name: 'Health &\nFitness',
        icon: { family: 'materialcommunity', name: 'heart' },
        colour: 'GREEN',
        habits: [
            {
                id: 'Go for a run',
                icon: { family: 'materialcommunity', name: 'run' },
                name: 'Go for a run',
                colour: 'PURPLE',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Go for a walk',
                icon: { family: 'materialcommunity', name: 'walk' },
                name: 'Go for a walk',
                colour: 'AQUA',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Eat fruit & vegetables',
                icon: { family: 'materialcommunity', name: 'food-apple' },
                name: 'Eat fruit & vegetables',
                colour: 'LIME',
                total: 4,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Drink water',
                icon: { family: 'materialcommunity', name: 'beer' },
                name: 'Drink water',
                colour: 'SKY',
                total: 5,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Lift weights',
                icon: { family: 'materialcommunity', name: 'dumbbell' },
                name: 'Lift weights',
                colour: 'ORANGE',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Stretch',
                icon: { family: 'materialcommunity', name: 'yoga' },
                name: 'Stretch',
                colour: 'YELLOW',
                total: 300,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'time',
                reminders: [],
            },
            {
                id: 'Walk the dog',
                icon: { family: 'materialcommunity', name: 'dog-service' },
                name: 'Walk the dog',
                colour: 'TANGERINE',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
        ],
    },
    wellbeing: {
        id: 'wellbeing',
        name: 'Mental\nWellbeing',
        icon: { family: 'materialcommunity', name: 'flower-tulip' },
        colour: 'PURPLE',
        habits: [
            {
                id: 'Meditate',
                icon: { family: 'materialcommunity', name: 'meditation' },
                name: 'Meditate',
                colour: 'MIDNIGHT',
                total: 300,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'time',
                reminders: [],
            },
            {
                id: 'Clean',
                icon: { family: 'materialcommunity', name: 'broom' },
                name: 'Clean',
                colour: 'PURPLE',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Reflect on my day',
                icon: { family: 'materialcommunity', name: 'weather-hazy' },
                name: 'Reflect on my day',
                colour: 'PINK',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Take a deep breath',
                icon: { family: 'materialcommunity', name: 'weather-windy' },
                name: 'Take a deep breath',
                colour: 'BLUE',
                total: 5,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Go outside',
                icon: { family: 'materialcommunity', name: 'pine-tree' },
                name: 'Go outside',
                colour: 'LIME',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Garden',
                icon: { family: 'materialcommunity', name: 'watering-can' },
                name: 'Garden',
                colour: 'GREEN',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Watch the sunset',
                icon: { family: 'materialcommunity', name: 'weather-sunset' },
                name: 'Watch the sunset',
                colour: 'TANGERINE',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
        ],
    },
    intellect: {
        id: 'intellect',
        name: 'Intellectual\nGrowth',
        icon: { family: 'materialcommunity', name: 'brain' },
        colour: 'ORANGE',
        habits: [
            {
                id: 'Read a book',
                icon: { family: 'materialcommunity', name: 'book-open-variant' },
                name: 'Read a book',
                colour: 'ORANGE',
                total: 600,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'time',
                reminders: [],
            },
            {
                id: 'Practice a language',
                icon: { family: 'materialcommunity', name: 'flag' },
                name: 'Practice a language',
                colour: 'TANGERINE',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Practice an instrument',
                icon: { family: 'materialcommunity', name: 'piano' },
                name: 'Practice an instrument',
                colour: 'YELLOW',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Read a research paper',
                icon: { family: 'materialcommunity', name: 'school' },
                name: 'Read a research paper',
                colour: 'LIME',
                total: 600,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'time',
                reminders: [],
            },
            {
                id: 'Sleep early',
                icon: { family: 'materialcommunity', name: 'bed' },
                name: 'Sleep early',
                colour: 'MIDNIGHT',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Reflect on my day',
                icon: { family: 'materialcommunity', name: 'weather-hazy' },
                name: 'Reflect on my day',
                colour: 'PINK',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
        ],
    },
    organisation: {
        id: 'organisation',
        name: 'Organisation',
        icon: { family: 'materialcommunity', name: 'puzzle' },
        colour: 'PINK',
        habits: [
            {
                id: 'Plan for tomorrow',
                icon: { family: 'materialcommunity', name: 'calendar' },
                name: 'Plan my day',
                colour: 'RED',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Reflect on my day',
                icon: { family: 'materialcommunity', name: 'weather-hazy' },
                name: 'Reflect on my day',
                colour: 'PINK',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Clean',
                icon: { family: 'materialcommunity', name: 'broom' },
                name: 'Clean',
                colour: 'PURPLE',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Do the dishes',
                icon: { family: 'materialcommunity', name: 'bowl-mix' },
                name: 'Do the dishes',
                colour: 'SKY',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Work towards my goals',
                icon: { family: 'materialcommunity', name: 'star' },
                name: 'Work towards my goals',
                colour: 'BLUE',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
        ],
    },
    social: {
        id: 'social',
        name: 'Social\nDevelopment',
        icon: { family: 'materialcommunity', name: 'account-group' },
        colour: 'TANGERINE',
        habits: [
            {
                id: 'Speak to a loved one',
                icon: { family: 'materialcommunity', name: 'heart' },
                name: 'Speak to a loved one',
                colour: 'RED',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Listen to others',
                icon: { family: 'materialcommunity', name: 'ear-hearing' },
                name: 'Listen to others',
                colour: 'MIDNIGHT',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Encourage others',
                icon: { family: 'materialcommunity', name: 'account-heart' },
                name: 'Encourage others',
                colour: 'PINK',
                total: 3,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Catch up with a friend',
                icon: { family: 'materialcommunity', name: 'account-group' },
                name: 'Catch up with a friend',
                colour: 'LIME',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Play a social sport',
                icon: { family: 'materialcommunity', name: 'soccer' },
                name: 'Play a social sport',
                colour: 'GREEN',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Wish someone well',
                icon: { family: 'materialcommunity', name: 'account-voice' },
                name: 'Wish someone well',
                colour: 'AQUA',
                total: 3,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
        ],
    },
    diet: {
        id: 'diet',
        name: 'Food &\nDiet',
        icon: { family: 'materialcommunity', name: 'food-apple' },
        colour: 'SKY',
        habits: [
            {
                id: 'Eat fruit & vegetables',
                icon: { family: 'materialcommunity', name: 'food-apple' },
                name: 'Eat fruit & vegetables',
                colour: 'LIME',
                total: 4,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Drink water',
                icon: { family: 'materialcommunity', name: 'beer' },
                name: 'Drink water',
                colour: 'SKY',
                total: 5,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Reduce snacking',
                icon: { family: 'materialcommunity', name: 'peanut' },
                name: 'Reduce snacking',
                colour: 'YELLOW',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Eat less meat',
                icon: { family: 'materialcommunity', name: 'food-steak' },
                name: 'Eat less meat',
                colour: 'ORANGE',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Drink less alcohol',
                icon: { family: 'materialcommunity', name: 'glass-mug-variant' },
                name: 'Drink less alcohol',
                colour: 'RED',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Reduce salt intake',
                icon: { family: 'materialcommunity', name: 'shaker' },
                name: 'Reduce salt intake',
                colour: 'PURPLE',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
        ],
    },
    art: {
        id: 'art',
        name: 'Arts &\nCreativity',
        icon: { family: 'materialcommunity', name: 'palette' },
        colour: 'YELLOW',
        habits: [
            {
                id: 'Practice an instrument',
                icon: { family: 'materialcommunity', name: 'piano' },
                name: 'Practice an instrument',
                colour: 'YELLOW',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Practice painting',
                icon: { family: 'materialcommunity', name: 'palette' },
                name: 'Practice painting',
                colour: 'TANGERINE',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Practice drawing',
                icon: { family: 'materialcommunity', name: 'pencil' },
                name: 'Practice drawing',
                colour: 'ORANGE',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Review a movie',
                icon: { family: 'materialcommunity', name: 'movie' },
                name: 'Review a movie',
                colour: 'RED',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Take a photo',
                icon: { family: 'materialcommunity', name: 'camera' },
                name: 'Take a photo',
                colour: 'PURPLE',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Film a video',
                icon: { family: 'materialcommunity', name: 'video-vintage' },
                name: 'Film a video',
                colour: 'MIDNIGHT',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Write a short story',
                icon: { family: 'materialcommunity', name: 'book-open-variant' },
                name: 'Write a short story',
                colour: 'BLUE',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
        ],
    },
    finance: {
        id: 'finance',
        name: 'Financial\nIndependence',
        icon: { family: 'materialcommunity', name: 'finance' },
        colour: 'AQUA',
        habits: [
            {
                id: 'Monitor my budget',
                icon: { family: 'materialcommunity', name: 'finance' },
                name: 'Monitor my budget',
                colour: 'AQUA',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Deposit savings',
                icon: { family: 'materialcommunity', name: 'cash-multiple' },
                name: 'Deposit savings',
                colour: 'GREEN',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Reduce spending',
                icon: { family: 'materialcommunity', name: 'currency-usd-off' },
                name: 'Reduce spending',
                colour: 'LIME',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Research investments',
                icon: { family: 'materialcommunity', name: 'chart-line' },
                name: 'Research investments',
                colour: 'ORANGE',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Work towards my goals',
                icon: { family: 'materialcommunity', name: 'star' },
                name: 'Work towards my goals',
                colour: 'BLUE',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
        ],
    },
    thoughful: {
        id: 'thoughful',
        name: 'Being\nThoughtful',
        icon: { family: 'materialcommunity', name: 'weather-partly-cloudy' },
        colour: 'RED',
        habits: [
            {
                id: 'Speak to a loved one',
                icon: { family: 'materialcommunity', name: 'heart' },
                name: 'Speak to a loved one',
                colour: 'RED',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Listen to others',
                icon: { family: 'materialcommunity', name: 'ear-hearing' },
                name: 'Listen to others',
                colour: 'MIDNIGHT',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Encourage others',
                icon: { family: 'materialcommunity', name: 'account-heart' },
                name: 'Encourage others',
                colour: 'PINK',
                total: 3,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Wish someone well',
                icon: { family: 'materialcommunity', name: 'account-voice' },
                name: 'Wish someone well',
                colour: 'AQUA',
                total: 3,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Show up on time',
                icon: { family: 'materialcommunity', name: 'clock' },
                name: 'Show up on time',
                colour: 'ORANGE',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
        ],
    },
    thankful: {
        id: 'thankful',
        name: 'Being\nThankful',
        icon: { family: 'materialcommunity', name: 'account-heart' },
        colour: 'BLUE',
        habits: [
            {
                id: 'Speak to a loved one',
                icon: { family: 'materialcommunity', name: 'heart' },
                name: 'Speak to a loved one',
                colour: 'RED',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Watch the sunset',
                icon: { family: 'materialcommunity', name: 'weather-sunset' },
                name: 'Watch the sunset',
                colour: 'TANGERINE',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Wish someone well',
                icon: { family: 'materialcommunity', name: 'account-voice' },
                name: 'Wish someone well',
                colour: 'AQUA',
                total: 3,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Smile',
                icon: { family: 'materialcommunity', name: 'emoticon' },
                name: 'Smile',
                colour: 'YELLOW',
                total: 5,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
            {
                id: 'Express gratitude',
                icon: { family: 'materialcommunity', name: 'emoticon-kiss' },
                name: 'Express gratitude',
                colour: 'ORANGE',
                total: 1,
                schedule: { ...EVERYDAY_SCHEDULE },
                dates: {},
                type: 'count',
                reminders: [],
            },
        ],
    },
};
